### ISSUE TITLE
What is the correct host/port name to use in local development?

### ISSUE THREAD

**Issue by LAMike310** [turtlecoin/turtlecoin-walletd-rpc-js#2]
I'm trying to follow the example in the ReadMe with my own local node.

I created a wallet with:

`./walletd -w test.wallet -p any_password_you_want -g`

and launched walletd with: 

`./walletd -w test.wallet -p any_password_you_want --local --rpc-password test`

Then I copied the code in the ReadMe and filled it in with what I think are the right params:

`var walletd = new TurtleCoinWalletd(
  "http://localhost",
  11898,
  "test"
);
`
When I run the `getViewKey` function I get this error:

`error -  TypeError: _popsicle2.default.get is not a function`

Am I calling the correct ports/hostname? I've tried `127.0.0.1` and `0.0.0.0` but I get the same issue.

Full gist with the example code from the ReadMe https://gist.github.com/LAMike310/64d27143fd5a6865e625ccdf2f8885b8

**Comment by BebopTC** [comment]
What you're doing is correct. this bug slipped in last night but should be fixed already by 1112ee4611ec0d7f2a10907035db46739c1cca9a. If you're cloning from the repo, do a `git pull`to get the latest. if you're using npm, reinstall the npm package to get latest version.
